### ISSUE TITLE
Shipped with invalid signature file

### ISSUE THREAD

**Issue by andk** [jackdeguest/CLASS#1]
This happens for me in the root directory of the untarred distro:

% cpansign -v
==> MALFORMED Signature file! <==

The SIGNATURE file is cut off before its end, meaning it does not contain an actual signature.

**Comment by andk** [comment]
Sorry, I forgot to mention the exact tarball I refer to: JDEGUEST/CLASS-v1.1.7.tar.gz

**Comment by jackdeguest** [comment]
Thank you for this. I have corrected it in the new version `v1.1.8`
